#!/bin/bash

License="
MIT License

Copyright (c) 2020 joseph touzet

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the \"Software\"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"

print_usage() {
  printf "$License
Usage: \" sudo init target1 target2 ... \"
	-a install all targets

  -h help
"
}

if [ ! -d "/etc/git-cli-utils/" ]; then
	mkdir /etc/git-cli-utils/
fi

param=$*

while getopts 'hau' flag; do
  case "${flag}" in
    h) print_usage;
      exit 1;;
		a) param=*;;
		u) param=$(</etc/git-cli-utils/installed.conf);;
  esac
done

cd ./cmds

echo "installing base ..."
cd ./base && bash ./init && cd ..
echo ""

echo "" > /etc/git-cli-utils/installed.conf

for directory in $param; do
	if [[ ! "$directory" -ef ./base ]] ; then
		echo "$directory " >> /etc/git-cli-utils/installed.conf

		echo "installing $directory ..."
		cd $directory && bash ./init && cd ..
		echo ""
	fi
done

cd ..
