#!/bin/bash

if [ "$(id -un)" != "root" ]; then
    echo "root privilege needed..."
    exit 1
fi

if [ ! -f "/etc/git-cli-utils/3dPrinting/params.json" ]; then
	echo "creating /etc/git-cli-utils/3dPrinting"
	mkdir /etc/git-cli-utils/3dPrinting
	echo '{"axis": "Z", "scaling_factor": 1.0, "base_height": 0.0, "offset": 0.0}' > /etc/git-cli-utils/3dPrinting/params.json
fi

for filename in *; do
	if [[ ! "$filename" -ef ./init ]] ; then
		echo "copying $filename to /usr/bin/$filename ..."

		chmod +x $filename && \
		cp $filename /usr/bin/
	fi
done
