#!/bin/bash

License="MIT License

Copyright (c) 2020 joseph touzet

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the \"Software\"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"

print_usage() {
  printf "$License
Usage: \"gitkey -u github_username -e github_email@mail.com -N passphrase -f key/file/name\"
  -u github username (mendatory)
  -e github email (mendatory)
  -N ssh key passphrase
  -f ssh key file name

  -h help
"
}

username=""
email=""
passphrase='""'
filename="github_key"

while getopts 'u:e:fN' flag; do
  case "${flag}" in
    h) print_usage;
      exit 1;;
  	u) username="${OPTARG}";;
    e) email="${OPTARG}";;
    N) passphrase="${OPTARG}";;
    f) filename="${OPTARG}";;
    *) print_usage;
       exit 1 ;;
  esac
done

echo $filename
echo $username
echo $email

file="/home/$(whoami)/.ssh/$filename"

git config --global user.name $username
git config --global user.email $email

ssh-keygen -o -E md5 -f $file -N $passphrase -t rsa -C $email

eval `ssh-agent -s`
ssh-add $file

key="$(cat $file.pub)"

echo $key
echo "add this key to https://github.com/settings/keys"
