#!/bin/bash

if [ "$(id -un)" != "root" ]; then
    echo "root privilege needed..."
    exit 1
fi

for filename in *; do
	if [[ ! "$filename" -ef ./init ]] ; then
		echo "copying $filename to /usr/bin/$filename ..."

		chmod +x $filename && \
		cp $filename /usr/bin/
	fi
done
