#!/bin/bash

echo "checking if appimagelauncher is installed ..."

if ! res="$(type -p "ail-cli")" || [[ -z $res ]]; then
	echo "installing appimagelauncher ..."

	add-apt-repository -y ppa:appimagelauncher-team/stable && \
	apt update -y && \
	apt install -y appimagelauncher
fi

for directory in $*; do
	echo "going through $directory ..."

	for filename in $directory/*; do
		echo "found $filename"

		if [[ $filename =~ \.deb$ ]]; then
			echo "installing $filename..."

			apt install -y $filename
		fi

		if [[ $filename =~ \.AppImage$ ] || [ $filename =~ \.appimage$ ]]; then
			echo "integrating $filename..."

			chmod +x $filename && \
			ail-cli integrate $filename && \
			cd $directory
		fi
	done
done
