#!/bin/bash

License="
MIT License

Copyright (c) 2020 joseph touzet

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the \"Software\"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"

print_usage() {
  printf "$License
Usage: \" sudo smbcreate -n share_name -f share_path -u share_allowed_user \"
  -n share name (mendatory)
  -f share path (mendatory)
  -u allowed user (if not specified will be $(whoami))

  -h help
"
}

echo "checking if samba is installed ..."

if ! res="$(type -p "samba")" || [[ -z $res ]]; then
	echo "installing samba ..."

	apt install -y samba
fi

user="$(whoami)"
name=""
path=""


while getopts 'n:f:uh' flag; do
  case "${flag}" in
    n) name="${OPTARG}";;
    f) path="${OPTARG}";;
    u) user="${OPTARG}";;
    *) print_usage
       exit 1 ;;
    h) print_usage;
      exit 1;;
  esac
done

param="\n
[$name]\n
\t        path = $path\n
\t        read only = no\n
\t        browseable = yes\n
\t        hide dot files = yes\n
\t        guest ok = no\n
\t        valid user = $user\n
\t        public = no\n
\t        create mode = 0777\n
\t        directory mode = 0777\n
\t        read raw = yes\n
\t        write raw = yes\n
\t        socket option = TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=131072 SO_SNDBUF=131072\n
\t        min receivefile size = 16384\n
\t        use sendfile = true\n
\t        aio read size = 16384\n
\t        aio write size = 16384\n
\t        getwd cache = true\n
\t        write cache size = 2097152\n"

smbpasswd -a $user && \
echo -e $param >> /etc/samba/smb.conf && \
service smbd restart
