#! /bin/bash
#
# Run parallel commands and fail if any of them fails.
# https://gist.github.com/mjambon/79adfc5cf6b11252e78b75df50793f24
#

set -eu

pids=()

for x in 1 2 3; do
  ls /not-a-file &
  pids+=($!)
done

for pid in "${pids[@]}"; do
  wait "$pid"
done
